### ISSUE TITLE
[FEATURE] Register API

### ISSUE THREAD

**Issue by SPiercer** [Piltover-s-Finest/be-safe#17]
### Summary : 
Implement a working login flow

### Requirements : 
1. Integrate the Register API 
2. Handle client side validation
3. Handle all kind of response errors

### Expected Results : 
The user will be able to face validation error if the following cases are met
- Empty Fields
- Incorrect email format
- short or weak password

---
#### References and links

API path: `/account/registerPatient`
##### Request body: 
```json
{
   "name": string,
   "email": string,
   "phoneNumber": string,
   "password": string,
   "address": string
}
```
> password must be 6 chars containing upper or lower case, numbers and special cases
##### Response types
200: 
```
number
```
> After a successful API call redirect the user to the OTP screen

400: Bad request
```json
{
   "errors": [
     string
   ],
   "status": 400,
   "message": "Validation failed. Please check your input data."
}
```

409: conflict
```json
{
   "status": 409,
   "message": string
}
```

**Comment by MahmoudAhmed2003** [comment]
how to validate the password

**Comment by MahmoudAhmed2003** [comment]
what is the response of the success API.?
just an Integer?

**Comment by SPiercer** [comment]
> what is the response of the success API.?
> just an Integer?

Yes, it's not needed just redirect the user to the otp screen

**Comment by SPiercer** [comment]
> how to validate the password 
> 

use the package queen_validators from pub.dev and apply validation rules

**Comment by MahmoudAhmed2003** [comment]
> > how to validate the password
> 
> use the package queen_validators from pub.dev and apply validation rules

i used it
but it doesn't have a validate for the numbers , special characters , upper case and lower case letters

**Comment by SPiercer** [comment]
Ok thanks for putting this out.

For our case here we have a password criteria strategy and in order to apply this strategy into a text we're are going to use Regular Expressions (Regex)


so the regex to use is 
`r'^(?=.*[A-Z])(?=.*[!@#$&*])(?=.*[0-9])(?=.*[a-z]).{8}$'`

-Explanation:

`^`                         Start anchor
`(?=.*[A-Z])`        Ensure string has one uppercase letter.
`(?=.*[!@#$&*])`            Ensure string has one special case letter.
`(?=.*[0-9])`        Ensure string has one digit.
`(?=.*[a-z])`   Ensure string has one lowercase letter.
`.{8}`                      Ensure string is of length 8.
`$`                        End anchor.
