### ISSUE TITLE
[CHORE] Create API prep classes

### ISSUE THREAD

**Issue by SPiercer** [Piltover-s-Finest/be-safe#19]
### Summary : 
Before we start handling any tickets that is related to API calls we must have a good API client and wrapper with a global repository for simplicity 

**What's an HTTP client ?**
It's a class that handles basic API calls and returns the response object

**What's an API wrapper ?**
It's a function that parses the response to return the correct response or a custom made API exception for server exceptions

**Why?**
because we don't have to write the exception handling logic every time for every api function we create.

**What's a Repository?**
It's a class that has all the API functions 

### Requirements : 
1. Create a `dio` HTTP client class that handles `GET`, `POST`, `PUT` and `DELETE` methods.
2. Create a base server exception class that parses the message and error list from the error response.
3. Create an API wrapper that parses the HTTP calls.

### Expected Results : 
A working HTTP client, exception class and API wrapper function.
alongside with its valid flows

---
#### References and links

baseURL : `http://minamagdy-001-site1.ktempurl.com/api`
https://pub.dev/packages/dio

If you have any further questions please comment in this ticket.

**Comment by isaacmalak** [comment]
explain it with more details like for example what is the parsing you are talking about and who is the api client ? 
please explain the entire ticket

**Comment by SPiercer** [comment]
This is the API client #20

the wrapper is just a function that parses the error into human readable output

to do so we create an abstract class that is called `APIException` that extends from the `Exception` class
that has three properties

1. Message
2. Error list
3. Code

for example

if a simple server error object looks like this

```json
{
  "message": "Some error ocurred",
  "status": 405
}
```

then we can create a custom class that extends from `APIException` called `ServerException`
that only overrides the message and the code

another example

if a validation exception object looks like this

```json
{
  "message": "Validation error please check your data",
  "errors": ["Your email address is incorrect", "Your password is weak"],
  "status": 400
}
```

we also can do the same and name it `ValidationException`

---

and then inside the function we call api wrapper is to simply try and catch the base `DioException` and parse it to either a `ServerException` or a `ValidationException`

then inside our repository where our api calls lies we call our api inside this api wrapper

```dart
Future<List> fetchData(){
   return apiHandler(() => dioClient.get(.....));
}
```

and in our logic layer we only try and catch on `ApiException` not any other exceptions

```dart
try{
   await repository.fetchData();
}on ApiException catch(e) {
   print(e.message);
   ValidationDialog.show(e.errors);
}
```
