### ISSUE TITLE
Fix OTP Screen

### ISSUE THREAD

**Issue by SPiercer** [Piltover-s-Finest/be-safe#8]
### Summary :
The OTP screen is trash and he's using four different text fields which is wrong

### Requirements : 
Remove the four text fields and use a Pinput widget

### Expected result :
Same UI with the same experience but the ability to get the OTP via the pinput controller

----
#### References and links
https://pub.dev/packages/pinput

**Comment by isaacmalak** [comment]
1. I cant style the filled button as you asked 
2. how I suppose to make a controller for the pin i didnt understand how i work with it from the references

**Comment by SPiercer** [comment]
https://pub.dev/packages/pinput#:~:text=Tips-,Controller,-///%20Create%20Controller

wrap the FilledButton inside of a sized box and give it maximum width  and kept it as it

**Comment by isaacmalak** [comment]
#22
